### ISSUE TITLE
TypeError: $ is not a function

### ISSUE THREAD

**Issue by AquariusPower** [ucnv/diff-for-gist.github#1]
on greasemonkey for firefox I get this:
```
Script error in [Greasemonkey script http://userscripts.org/users/40991/Diff for gist.github]:
TypeError: $ is not a function
```
btw, it is only accessible thru the mirror
https://userscripts-mirror.org/scripts/review/62706

but, I think this is not necessary as it is implemented on gist thru revisions, despite it is hard to read change logs between two forks. This script is not about comparing forks is it?

**Comment by ucnv** [comment]
Hey @AquariusPower
Thanks for your message.
This is very old script. At that time the gist had no diff function yet, so I wrote this as a tweak.
It logged like https://github.blog/2010-01-27-diff-your-gist/
After the gist implemented diff, it became out of date. This repo is dead without maintenance.
